### ISSUE TITLE
LocateAnchorsCompleted event handler on SpatialAnchorManager is invoked before anchor location is complete.

### ISSUE THREAD

**Issue by sublimeRich** [Azure/azure-spatial-anchors-samples#112]
When trying to locate more than one anchor by providing multiple identifiers to `AnchorLocateCriteria`, the `SpatialAnchorManager` will fire the `AnchorLocated` and the `LocateAnchorsCompleted` events in an incorrect order, eg 

AnchorLocate <anchor 1>
AnchorLocate <anchor 2>
LocateAnchorComplete
AnchorLocate <anchor 3>

The `LocateAnchorComplete` event appears to always be fired after the first anchor is located, but usually before the final anchor is found.  In my test case, I had three anchors within one room, a couple of meters apart.

Using SDK version 2.1.1 on Android; I can't reproduce the issue on Hololens.

**Comment by julianparismorgan** [comment]
Hi @sublimeRich, thanks for letting us know. We're looking into this!

**Comment by tomkrikorian** [comment]
Any progress @julianparismorgan ?

**Comment by darax** [comment]
Wow... fixing this would be really tricky. Here is what is happening:
when SpatialAnchorManager gets an AnchorLocated from ASA on Droid/iOS it puts the anchor in a queue.  This is because ARFoundation keeps track of the anchors on these platforms, and it can be a frame or two in finding the anchor that ASA created for the anchor located result.  The processing of that queue is every update we ask ARFoundation if it knows about the anchor, and if it does, /then/ we send the anchor located event to your script. 

The AnchorsLocatedCompleted event, however doesn't know about this delay in the location events. I guess to fix this I would need to set a bool in SpatialAnchorManager when ASA sends locate completed, and then when processing the Locate queue, I can fire the locate completed event if the queue is empty and the locate completed flag is set.

So, I guess that's progress on a fix. :)

**Comment by Varnauld** [comment]
Hello,
I closed this item as this was originally submitted close to two years ago. Our latest release is available [here](https://github.com/Azure/azure-spatial-anchors-samples/releases/tag/v2.12.0) – please re-open this item should you have further feedback for the team.
Alternatively, if you have any ideas or requests for new features or capabilities, or should you wish to upvote an existing idea, please visit our [Feedback hub](https://feedback.azure.com/d365community/forum/f47d9b25-0725-ec11-b6e6-000d3a4f07b8)

Thank you

**Comment by Silloty1** [comment]
Hello,

Currently on the v.2.12.0 for ASA, the bug is currently here.
It seems like the event AnchorsLocatedCompleted is triggered before all anchors are correctly located

**Comment by Varnauld** [comment]
Hello @Silloty1 - we released 2.13.0 mid-July. Have you had the opportunity to test again? Thank you for any further insights you can provide. https://github.com/Azure/azure-spatial-anchors-samples/releases

**Comment by Silloty1** [comment]
Hello @Varnauld
I will test this and I will let you know

**Comment by Silloty1** [comment]
Hello @Varnauld 

Just did some tests!
As far as I understand, the event is correctly triggered if anchors are found by Visual Information.
Somehow, if the watcher locate strategy is Any, as soon as one anchor will be recognized, the event will be triggered, and all other anchors will be found by relationship afterwards. 

By default, our locate strategy is any, so I couldn't really get why the event was triggered too early. After modifying my code and specifying the locate strategy to Visual Information, the event was triggered correctly

**Comment by Varnauld** [comment]
Hi @Silloty1 thank you for sharing your update! I'm tagging @XiangyuL-Microsoft should you have any further follow up questions here, but it sounds like you were able to resolve your issue? thank you

**Comment by blahgyn** [comment]
Hello.
In Unity, the bug still happens in version 2.12 and 2.14.1. 
I noticed that the LocateAnchorsCompleted is **not** on the main thread, while AnchorLocated is. This probably explain the lack of order consistency.
