### ISSUE TITLE
Unity Android build CloudSpatialException

### ISSUE THREAD

**Issue by MarcinKulwicki** [Azure/azure-spatial-anchors-samples#155]
I running sample project on MacOS, i downloaded the project using github command
Set up on the Scene AzureSpatialAnchorsBasicDemo/AzureSpatialAnchors the Account Id And Account Key.
Set up Account Key and Account Id in AzureSpatialAnchors.SDK/Resources/SpatialAnchorConfig
Grant in Application Settings on Phone access to memory and localization

Firstly i try on Unity 2019.1.10 and AR Fundation 2.2.0 prev 2
Now i trying on Unity 2019.3.0f6 and
```
    "com.unity.xr.arcore": "2.2.0-preview.6",
    "com.unity.xr.arfoundation": "2.2.0-preview.6",
    "com.unity.xr.arkit": "2.2.0-preview.6",
    "com.unity.xr.arsubsystems": "2.2.0-preview.6",
```
Still the same error. Any idea?

Full error

```
2020-04-15 00:06:15.985 30354-30427/? E/Unity: CloudSpatialException
      at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00180] in <b30c8119b19f43978cde6dd2a9f6c77f>:0 
      at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession+<>c__DisplayClass82_0.<CreateAnchorAsync>b__0 () [0x00035] in <b30c8119b19f43978cde6dd2a9f6c77f>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <7d97106330684add86d080ecf65bfe69>:0 
      at System.Threading.Tasks.Task.Execute () [0x00010] in <7d97106330684add86d080ecf65bfe69>:0 
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <7d97106330684add86d080ecf65bfe69>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <7d97106330684add86d080ecf65bfe69>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading
2020-04-15 00:06:15.987 30354-30427/? I/Unity: Failed to save anchor Microsoft.Azure.SpatialAnchors.CloudSpatialException
      at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00180] in <b30c8119b19f43978cde6dd2a9f6c77f>:0 
      at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession+<>c__DisplayClass82_0.<CreateAnchorAsync>b__0 () [0x00035] in <b30c8119b19f43978cde6dd2a9f6c77f>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <7d97106330684add86d080ecf65bfe69>:0 
      at System.Threading.Tasks.Task.Execute () [0x00010] in <7d97106330684add86d080ecf65bfe69>:0 
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <7d97106330684add86d080ecf65bfe69>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <7d97106330684add86d080ecf65bfe69>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.Hand
```

**Comment by SvenDeha** [comment]
You are not alone, we are having exactly the same issue. Unity Android build with the quickstart followed. Hoping someone could provide a solution for this.

**Comment by tomkrikorian** [comment]
Also having a lot of issues on android when creating anchors.

You should add the ErrorCode to your log to have more information about why it failed :
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.spatialanchors.cloudspatialexception.errorcode#Microsoft_Azure_SpatialAnchors_CloudSpatialException_ErrorCode

**Comment by darax** [comment]
for 2019.1 try updating to the latest preview ARFoundation and ARCoreXR packages available. For 2019.3, please see https://github.com/Azure/azure-spatial-anchors-samples/issues/149.  It would be good to see the exception code for failing to create the anchor.  Are you waiting for the sessionStatus to report ReadyToCreateProgress >= 1?

**Comment by darax** [comment]
starting to look like this might be a general issue with recently created resources.  Our service team is investigating.

**Comment by darax** [comment]
@tomkrikorian  @SvenDeha @MarcinKulwicki There was a service outage with resources that hadn't created their first anchor failing to create an anchor. This should be mitigated now.

**Comment by tomkrikorian** [comment]
Thanks @darax

**Comment by MarcinKulwicki** [comment]
Why you closed? Come on. I will have some time in weekend

**Comment by darax** [comment]
@MarcinKulwicki 5 people (in two separate issue threads) had this same error caused by a service outage that has been fixed. 3 out of 5 have reported that the issue is resolved for them.  I took this as evidence of resolution.

**Comment by MarcinKulwicki** [comment]
I try with new project 
1) Unity 2019.1.10 
```
"com.unity.xr.arcore": "2.2.0-preview.6",
    "com.unity.xr.arfoundation": "2.2.0-preview.6",
    "com.unity.xr.arkit": "2.2.0-preview.6",
    "com.unity.xr.arsubsystems": "2.2.0-preview.6",
```
2) Unity 2019.3.0f6 and instruction https://github.com/Azure/azure-spatial-anchors-samples/issues/149

I set up in both case Spatial Anchors Account Id and Spatial Anchors Account Key in scene AzureSpatialAnchorsBasicDemo and in AzureSpatialAnchors.SDK/Resources/SpatialAnchorConfig

And still have the same error. At the beginning, after open app:
```
2020-04-18 18:33:22.069 6346-6431/? E/Unity: A scripted object (probably UnityEngine.XR.WSA.SpatialMappingCollider?) has a different serialization layout when loading. (Read 32 bytes but expected 100 bytes)
    Did you #ifdef UNITY_EDITOR a section of your serialized properties in any of your scripts? 
    (Filename:  Line: 2269)
2020-04-18 18:33:22.103 6346-6426/? E/Unity: -------- GLSL link error:  The number of vertex shader storage blocks (1) is greater than the maximum number allowed (0).
```

and next 

```
2020-04-18 18:33:58.796 6346-6379/? E/Unity: CloudSpatialException
      at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00180] in <3c35eaed12924cb4954ec96eb36797ad>:0 
      at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession+<>c__DisplayClass82_0.<CreateAnchorAsync>b__0 () [0x00035] in <3c35eaed12924cb4954ec96eb36797ad>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <437ba245d8404784b9fbab9b439ac908>:0 
      at System.Threading.Tasks.Task.Execute () [0x00010] in <437ba245d8404784b9fbab9b439ac908>:0 
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <437ba245d8404784b9fbab9b439ac908>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <437ba245d8404784b9fbab9b439ac908>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading
2020-04-18 18:33:58.799 6346-6379/? I/Unity: Failed to save anchor Microsoft.Azure.SpatialAnchors.CloudSpatialException
      at Microsoft.Azure.SpatialAnchors.NativeLibraryHelpers.CheckStatus (System.IntPtr handle, Microsoft.Azure.SpatialAnchors.status value) [0x00180] in <3c35eaed12924cb4954ec96eb36797ad>:0 
      at Microsoft.Azure.SpatialAnchors.CloudSpatialAnchorSession+<>c__DisplayClass82_0.<CreateAnchorAsync>b__0 () [0x00035] in <3c35eaed12924cb4954ec96eb36797ad>:0 
      at System.Threading.Tasks.Task.InnerInvoke () [0x0000f] in <437ba245d8404784b9fbab9b439ac908>:0 
      at System.Threading.Tasks.Task.Execute () [0x00010] in <437ba245d8404784b9fbab9b439ac908>:0 
    --- End of stack trace from previous location where exception was thrown ---
      at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <437ba245d8404784b9fbab9b439ac908>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <437ba245d8404784b9fbab9b439ac908>:0 
      at System.Runtime.CompilerServices.TaskAwaiter.Hand
```
